apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: landing-route
  namespace: landing
spec:
  parentRefs:
    - name: main-gateway
      namespace: default
      sectionName: https-root
  hostnames:
    - etcd.me
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: landing
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: landing-http-redirect
  namespace: landing
spec:
  parentRefs:
    - name: main-gateway
      namespace: default
      sectionName: http-root
  hostnames:
    - etcd.me
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
